name:                epistemic-group-gossip
version:             0.1.0.0
github:              "RamonMeffert/epistemic-group-gossip"
license:             BSD3
author:              "Jesper Kuiper, Leander van Boven and Ramon Meffert"
maintainer:          "example@example.com"
copyright:           "2021 Jesper Kuiper, Leander van Boven and Ramon Meffert"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/RamonMeffert/epistemic-group-gossip#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6
- HasCacBDD >= 0.1.0.3 && < 0.2
# - cudd == 0.1.0.0
# - smcdel >= 1.1.0
- fgl >=5.7.0.3
- text >= 1.2.4.1
- ansi-terminal >= 0.10.3

library:
  source-dirs: src/

executables:
  egg:
    main:                Main.hs
    source-dirs:         app/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - epistemic-group-gossip

tests:
  egg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - epistemic-group-gossip
