name: Continous Integration
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install stack (Windows)
        run: choco install haskell-stack
        if: matrix.os == 'windows-2019'

      - name: Cache dependencies (Unix)
        uses: actions/cache@v1
        if: matrix.os != 'windows-2019'
        with:
          path: ~/.stack
          key: ${{ runner.os }}-store-${{ hashFiles('./stack.yaml.lock') }}-${{ hashFiles('./generator.cabal') }}

      - name: Cache dependencies (Windows)
        uses: actions/cache@v1
        if: matrix.os == 'windows-2019'
        with:
          path: 'C:\Users\runneradmin\AppData\Roaming\stack'
          key: ${{ runner.os }}-store-${{ hashFiles('./stack.yaml.lock') }}-${{ hashFiles('./generator.cabal') }}

      - name: Cache GHC (Windows)
        uses: actions/cache@v1
        if: matrix.os == 'windows-2019'
        with:
          path: 'C:\Users\runneradmin\AppData\Local\Programs\stack'
          key: ghc-${{ hashFiles('./stack.yaml.lock') }}

      - name: Build egg
        run: stack build

      - name: Package egg
        shell: bash
        run: |
          mkdir package
          dir=$(stack path --dist-dir)/build/egg
          [[ -e "$dir/egg" ]] && cp "$dir/egg" package/Egg
          
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: egg-${{ runner.os }}
          path: package
          
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v1
        with:
          name: egg-Linux
          path: artifacts/egg-Linux
      
      - name: Download MacOS artifact
        uses: actions/download-artifact@v1
        with:
          name: egg-macOS
          path: artifacts/egg-macOS
    
      - name: Create automatic release
        id: automatic_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: Latest release ${{ runner.os }}
          prerelease: false
          draft: false
          files: |
            LICENSE
            artifacts/egg-Linux
            artifacts/egg-macOS
      
      
