name: Continous Integration
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      -main
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install stack (Windows)
        run: choco install haskell-stack
        if: matrix.os == 'windows-2019'

      - name: Cache dependencies (Unix)
        uses: actions/cache@v1
        if: matrix.os != 'windows-2019'
        with:
          path: ~/.stack
          key: ${{ runner.os }}-store-${{ hashFiles('./stack.yaml.lock') }}-${{ hashFiles('./generator.cabal') }}

      - name: Cache dependencies (Windows)
        uses: actions/cache@v1
        if: matrix.os == 'windows-2019'
        with:
          path: 'C:\Users\runneradmin\AppData\Roaming\stack'
          key: ${{ runner.os }}-store-${{ hashFiles('./stack.yaml.lock') }}-${{ hashFiles('./generator.cabal') }}

      - name: Cache GHC (Windows)
        uses: actions/cache@v1
        if: matrix.os == 'windows-2019'
        with:
          path: 'C:\Users\runneradmin\AppData\Local\Programs\stack'
          key: ghc-${{ hashFiles('./stack.yaml.lock') }}

      - name: Build egg
        run: stack build --haddock --no-haddock-deps

      - name: Package egg
        shell: bash
        run: |
          mkdir package
          dir=$(stack path --dist-dir)/build/egg
          [[ -e "$dir/egg" ]] && cp "$dir/egg" package/Egg-${{ runner.os }}
          
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: egg-${{ runner.os }}
          path: package
          
      - name: Find Haddock docs path
        run: echo "DOCS_DIR=$(stack path --local-doc-root)" >> $GITHUB_ENV
        id: find-docs
        if: matrix.os == 'ubuntu-18.04'
        
      - name: Publish Haddock docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: matrix.os == 'ubuntu-18.04'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.DOCS_DIR }}
          destination_dir: './docs'
          enable_jekyll: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Update docs (automatic)'
  
  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v1
        with:
          name: egg-Linux
          path: artifacts/egg-Linux
      
      - name: Download MacOS artifact
        uses: actions/download-artifact@v1
        with:
          name: egg-macOS
          path: artifacts/egg-macOS
    
      - name: Create automatic release
        id: automatic_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: Latest release
          prerelease: false
          draft: false
          files: |
            artifacts/egg-Linux
            artifacts/egg-macOS
      
      
