name: Continous Integration
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install stack (MacOS)
        run: curl -sSL https://get.haskellstack.org/ | sh -s - -f
        if: matrix.os == 'macos-10.15'

      - name: Install stack (Windows)
        run: choco install haskell-stack
        if: matrix.os == 'windows-2019'

      - name: Cache dependencies (Unix)
        uses: actions/cache@v1
        if: matrix.os != 'windows-2019'
        with:
          path: ~/.stack
          key: ${{ runner.os }}-store-${{ hashFiles('./stack.yaml.lock') }}-${{ hashFiles('./generator.cabal') }}

      - name: Cache dependencies (Windows)
        uses: actions/cache@v1
        if: matrix.os == 'windows-2019'
        with:
          path: 'C:\Users\runneradmin\AppData\Roaming\stack'
          key: ${{ runner.os }}-store-${{ hashFiles('./stack.yaml.lock') }}-${{ hashFiles('./generator.cabal') }}

      - name: Cache GHC (Windows)
        uses: actions/cache@v1
        if: matrix.os == 'windows-2019'
        with:
          path: 'C:\Users\runneradmin\AppData\Local\Programs\stack'
          key: ghc-${{ hashFiles('./stack.yaml.lock') }}

      - name: Build egg
        run: stack build

      - name: Package egg
        shell: bash
        run: |
          mkdir package
          dir=$(stack path --dist-dir)/build/egg
          [[ -e "$dir/egg" ]] && cp "$dir/egg" package/Egg

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: egg-${{ runner.os }}
          path: package
          
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: egg-${{ runner.os }}
          path: egg-${{ runner.os }}
    
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "latest"
          release_name: "Latest release"
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: egg-${{ runner.os }}
          asset_name: egg-${{ runner.os }}
          asset_content_type: application/zip
